In [17]:
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression, Ridge,Lasso,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
#load the diabetes dataset
d=load_diabetes()
data=pd.DataFrame(data=d.data,columns=d.feature_names)
data.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204
2,0.085299,0.050680,0.044451,-0.005671,-0.045599,-0.034194,-0.032356,-0.002592,0.002864,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022692,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641

In [3]:
data['Target']=d.target
data.shape

(442, 11)

In [4]:
data.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,Target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005671,-0.045599,-0.034194,-0.032356,-0.002592,0.002864,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022692,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641,135.0

In [5]:
#select features and target
x=data.iloc[:, :-1]
y=data['Target']
#split the data into training and test sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=0)

In [7]:
l=LinearRegression()
#fit the model on training data set
l.fit(x_train,y_train)
#predict using linear regression
y_linear_pred_train=l.predict(x_train)
y_linear_pred=l.predict(x_test)

In [9]:
#create ridge model
r=Ridge(alpha=1.0)
#fit the model
r.fit(x_train,y_train)
#predict using ridge regression
y_ridge_pred_train=r.predict(x_train)
y_ridge_pred=r.predict(x_test)

In [13]:
#create lasso model
la=Lasso(alpha=1.0)
#fit the model
la.fit(x_train,y_train)
#predict using lasso  regression
y_lasso_pred_train=la.predict(x_train)
y_lasso_pred=la.predict(x_test)

In [18]:
#create ElasticNet model
e=ElasticNet()
#fit  the model
e.fit(x_train,y_train)
#predict using elastic net
y_elasticnet_pred_train=e.predict(x_train)
y_elasticnet_pred=e.predict(x_test)

In [19]:
#create mean squared errors for all  three models
#linear
mlt=mean_squared_error(y_train,y_linear_pred_train)
ml=mean_squared_error(y_test,y_linear_pred)
print('Linear Regression Results','\n')
print('Training error : ',mlt)
print('Testing error : ',ml)
print('Difference :',ml-mlt)
print('---------------------------------------------------')
#Ridge
mrt=mean_squared_error(y_train,y_ridge_pred_train)
mr=mean_squared_error(y_test,y_ridge_pred)
print('Ridge Regression Results','\n')
print('Training error : ',mrt)
print('Testing error : ',mr)
print('Difference :',mr-mrt)
print('---------------------------------------------------')
#lasso
mlat=mean_squared_error(y_train,y_lasso_pred_train)
mla=mean_squared_error(y_test,y_lasso_pred)
print('Lasso Regression Results','\n')
print('Training error : ',mlat)
print('Testing error : ',mla)
print('Difference :',mla-mlat)
print('---------------------------------------------------')
#ElasticNet
met=mean_squared_error(y_train,y_elasticnet_pred_train)
me=mean_squared_error(y_test,y_elasticnet_pred)
print('ElasticNet Regression Results','\n')
print('Training error : ',met)
print('Testing error : ',me)
print('Difference :',me-met)
print('---------------------------------------------------')

Linear Regression Results

Training error :  2734.729272403143
Testing error :  3424.316688213733
Difference : 689.5874158105898
---------------------------------------------------
Ridge Regression Results

Training error :  3279.398293151491
Testing error :  3379.4239650121217
Difference : 100.02567186063061
---------------------------------------------------
Lasso Regression Results

Training error :  3663.272442946559
Testing error :  3787.8964304403826
Difference : 124.62398749382373
---------------------------------------------------
ElasticNet Regression Results

Training error :  6069.188332118301
Testing error :  5093.823506648497
Difference : -975.3648254698046
---------------------------------------------------